version: '3.8'

services:

  app:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: always
    networks:
      - titan_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/lib/jenkins/workspace/Titan-Agil/public:/var/www/public
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - app
    networks:
      - titan_network

networks:
  titan_network:
    external: true