version: '3.8'

services:

  app:
  build:
    context: ..
    dockerfile: docker/php/Dockerfile
  restart: always
  networks:
    - titan_network

  nginx:
  image: nginx:latest
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx:/etc/nginx/conf.d
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - /var/www/certbot:/var/www/certbot
  depends_on:
    - app
  networks:
    - titan_network

  # 🔥 WORKER (FILA - ESSENCIAL)
  worker:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    # remove essa linha
    restart: always
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=600
    
    depends_on:
      - app
    networks:
      - titan_network

  # 🔥 SCHEDULER (CRON DO LARAVEL)
  scheduler:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    # remove essa linha
    restart: always
    command: sh -c "while true; do php artisan schedule:run; sleep 60; done"
    
    depends_on:
      - app
    networks:
      - titan_network

networks:
  titan_network:
    external: true