server {
    listen 80;
    server_name dash.agenciatitandev.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name dash.agenciatitandev.com;

    ssl_certificate /etc/letsencrypt/live/dash.agenciatitandev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dash.agenciatitandev.com/privkey.pem;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
        fastcgi_param HTTPS on;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|map)$ {
        expires 7d;
        access_log off;
    }

}

server {
    listen 80;
    server_name vsl.agenciatitandev.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name vsl.agenciatitandev.com;

    ssl_certificate /etc/letsencrypt/live/vsl.agenciatitandev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vsl.agenciatitandev.com/privkey.pem;

    location / {
        proxy_pass http://vsl_dashboard_app:8050;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
